package inori.roguecore.relic

enum class RelicEffectType {
    KILL_SHARD,
    ROOM_HEAL,
    LOW_HEALTH_DAMAGE,
    BONUS_LOOT_CHANCE,
    SHOP_DISCOUNT,
    BOSS_EMBER_BONUS,
    HIDDEN_KEY_CHANCE,
    COMBAT_START_SHIELD,
    ELITE_LOOT_CHANCE,
    SHOP_HEAL_DISCOUNT,
    SHOP_MATERIAL_BONUS,
    SHRINE_RELIC_BOOST,
    GAMBLE_INSURANCE,
    TRIAL_FORGE_BONUS,
    CHEST_MATERIAL_BONUS,
    HIDDEN_LOOT_BONUS,
    BOON_OFFER_BONUS,
    ROOM_UPGRADE_CHANCE,
    BOON_RARITY_LUCK,
    BOSS_LOOT_CHANCE,
    HIDDEN_RELIC_BOOST,
    ELITE_RELIC_CHANCE,
    BLACK_MARKET_DISCOUNT,
    CHEST_EXTRA_LOOT_CHANCE
}
